name: Python Build and Artifact Upload

on: workflow_dispatch

jobs:
  python_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package application
        run: |
          mkdir staging
          cp -r your_package_or_script.py staging/  # Replace with your actual file or folder

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: PythonPackage
          path: staging
